# Generated by Django 4.1.3 on 2022-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images')),
                ('details', models.TextField(verbose_name='Подробности')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
        ),
    ]
